pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Compile') {
            steps {
                dir('vehicle-parking') {
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('vehicle-parking') {
                    sh 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('vehicle-parking') {
                    sh 'mvn package'
                }
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'vehicle-parking/target/*.jar', fingerprint: true
            }
        }
    }

    post {
        always {
            junit testResults: 'vehicle-parking/target/surefire-reports/*.xml', allowEmptyResults: true
        }
    }
}
